# Generated by Django 3.1.3 on 2020-12-15 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(max_length=20)),
                ('info_mail', models.CharField(max_length=100)),
                ('info_txt', models.TextField()),
                ('info_status', models.CharField(default='0', max_length=1)),
                ('info_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('item_img', models.ImageField(null=True, upload_to='')),
                ('publish', models.CharField(max_length=100)),
                ('category_1', models.CharField(max_length=100)),
                ('category_2', models.CharField(max_length=100)),
                ('p_date', models.DateField(null=True)),
                ('stock', models.IntegerField(default=0, null=True)),
                ('isbn', models.IntegerField(null=True)),
                ('jan', models.IntegerField(null=True)),
                ('item_ex', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_fee', models.CharField(max_length=1)),
                ('shipping', models.CharField(max_length=1)),
                ('slip_status', models.CharField(default='0', max_length=1)),
                ('slip_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('review_txt', models.TextField()),
                ('review_date', models.DateField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.item')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1_code', models.IntegerField()),
                ('address1_prefecture', models.CharField(max_length=10)),
                ('address1_city', models.CharField(max_length=100)),
                ('address2_code', models.IntegerField(null=True)),
                ('address2_prefecture', models.CharField(max_length=10, null=True)),
                ('address2_city', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(default='0', max_length=1)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('card_num', models.CharField(max_length=16, null=True)),
                ('card_name', models.CharField(max_length=30, null=True)),
                ('card_limit', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_cnt', models.IntegerField(default=1)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.item')),
                ('slip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.slip')),
            ],
        ),
    ]
